stages:
  - build
  - test

variables:
  APPLICATION_NAME: mongoose-crud-rest-api
  GITLAB_REGISTRY: 172.16.98.151:5000
  DOCKER_IMAGE: $GITLAB_REGISTRY/$APPLICATION_NAME

api-build:
  stage: build
  script:
    - docker build -t ${DOCKER_IMAGE}-dev ./
    - docker push ${DOCKER_IMAGE}-dev

api-test:
  stage: test
  before_script:
    - echo Setting up network if does not exist
    - if [ -z "$(docker network ls | grep 'nodejs-tdd')" ]; then docker network create nodejs-tdd; fi
    - echo "Running database"
    - docker run --rm -d --name nodejs-tdd-db --network nodejs-tdd -h nodejs-tdd-db mongo:4.4.4
    - echo "Database is up"
  script:
    # Run test
    - >
      docker run
      --rm
      --name nodejs-tdd
      --network nodejs-tdd
      -e MONGODB_URL mongodb://nodejs-tdd-db
      ${DOCKER_IMAGE}-dev
      npm run test
  after_script:
    # Remove database and network
    - echo "Stopping test database"
    - docker container stop nodejs-tdd-db
    - echo "Stopped test database"
    - echo Removing network if exist
    - if [ -n "$(docker network ls | grep 'nodejs-tdd')" ]; then docker network rm nodejs-tdd; fi
